[theme]

primaryColor = '#009959' # Brand Green

backgroundColor = '#0C0F0B' # Blackish

secondaryBackgroundColor = '#101618' # Lighter Black

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"